### PR TITLE
Update AMIFlyingFishBoots.java

### PR DESCRIPTION
**Pull request by Brittank88**
Fix logspam

### CODE REVIEW

**Comment by Brittank88** [comment]
Oh btw, "fishyVaribale" is misspelt I think

**Comment by CrimsonCrips** [comment]
that is so embarassing of me lmao

thanks

**Comment by CrimsonCrips** [comment]
fuck

i didnt mean to close

**Comment by Brittank88** [comment]
> that is so embarassing of me lmao
> 
> thanks

Ahaha ur fine we all make mistakes

I had to build a sketchy random mod in record time using [StackDumper](https://diffplug.github.io/durian/javadoc/3.4.0/com/diffplug/common/base/StackDumper.html) just to figure out what mod was causing the issue, and then I thought it was Alex's Mobs because it was a mixin so it was coming from their mod even though it was AMI!!

**Pull request merged**
